os: osx
language: swift

branches:
  only:
  - master
  - develop

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

xcode_project: Logr.xcodeproj
xcode_scheme: Logr

jobs:
  include:
    - xcode_destination: platform=iOS Simulator,name=iPhone 6,OS=10.3.1
      osx_image: xcode11.5
    - xcode_destination: platform=iOS Simulator,name=iPhone 7,OS=11.4
      osx_image: xcode11.5
    - xcode_destination: platform=iOS Simulator,name=iPhone 8,OS=12.4
      osx_image: xcode11.5
    - xcode_destination: platform=iOS Simulator,name=iPhone 8,OS=13.2.2
      osx_image: xcode11.5

    - xcode_destination: platform=tvOS Simulator,name=Apple TV,OS=latest
      osx_image: xcode11.5
    - xcode_destination: platform=tvOS Simulator,name=Apple TV,OS=12.4
      osx_image: xcode11.5
    - xcode_destination: platform=tvOS Simulator,name=Apple TV,OS=11.4
      osx_image: xcode11.5
    - xcode_destination: platform=tvOS Simulator,name=Apple TV,OS=10.2
      osx_image: xcode11.5

    - xcode_destination: platform=iOS Simulator,name=iPhone 5s,OS=9.0
      osx_image: xcode10.2
      before_script:
        - sudo mkdir -p '/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift'
    - xcode_destination: platform=tvOS Simulator,name=Apple TV,OS=9.0
      osx_image: xcode10.2
      before_script:
        - sudo mkdir -p '/Library/Developer/CoreSimulator/Profiles/Runtimes/tvOS 9.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift'
        
    - xcode_destination: platform=OS X,arch=x86_64
      osx_image: xcode11.3
    - xcode_destination: platform=OS X,arch=x86_64
      osx_image: xcode11.5

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Logr'
