os: osx
osx_image: xcode10.3
language: swift

branches:
  only:
  - master
  - develop

brefore_install:
  - gem install xcpretty --no-document --quiet
  - xcpretty --version

script: 
  - xcodebuild clean build -project Logr.xcodeproj -scheme Logr -sdk iphonesimulator
    -destination "platform=iOS Simulator,OS=10.3,name=iPhone 8"
    -destination "platform=iOS Simulator,OS=12.4,name=iPhone X"
    test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Logr'
