os: osx
osx_image: xcode11.1
language: swift

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

branches:
  only:
  - master
  - develop

brefore_install:
  - gem install xcpretty --no-document --quiet
  - xcpretty --version

script: 
  - xcodebuild clean build -project Logr.xcodeproj -scheme Logr -destination 'platform=iOS Simulator,name=iPhone 5s,OS=10.3.1' | xcpretty -c
  - xcodebuild clean build -project Logr.xcodeproj -scheme Logr -destination 'platform=iOS Simulator,name=iPhone Xs,OS=latest' | xcpretty -c

  - xcodebuild test -project Logr.xcodeproj -scheme Logr -destination 'platform=iOS Simulator,name=iPhone 5s,OS=10.3.1' | xcpretty -c
  - xcodebuild test -project Logr.xcodeproj -scheme Logr -destination 'platform=iOS Simulator,name=iPhone Xs,OS=latest' | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Logr'
