os: osx
osx_image: xcode11.5
language: swift

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

branches:
  only:
  - master
  - develop

xcode_project: Logr.xcodeproj
xcode_scheme: Logr

jobs:
  include:
    - xcode_destination: platform=iOS Simulator,name=iPhone 6,OS=10.3.1
    - xcode_destination: platform=iOS Simulator,name=iPhone 7,OS=11.4
    - xcode_destination: platform=iOS Simulator,name=iPhone 8,OS=12.4
    - xcode_destination: platform=iOS Simulator,name=iPhone 8,OS=13.2.2

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Logr'
