os: osx
osx_image: xcode10.2
language: swift
script: xcodebuild clean build 
        -project Logr.xcodeproj -scheme Logr -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.2,name=iPhone X"
        test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Logr'