os: osx
language: swift

branches:
  only:
  - main
  - develop

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=.swiftpm/xcode/package.xcworkspace
    - SCHEME=Logr

jobs:
  include:
    - osx_image: xcode12.2
      env: DESTINATION='platform=iOS Simulator,name=iPhone 11,OS=14.2'
    - osx_image: xcode12.2
      env: DESTINATION='platform=iOS Simulator,name=iPhone 11,OS=13.5'
    - osx_image: xcode12.2
      env: DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=12.4'
    - osx_image: xcode12.2
      env: DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=11.4'
    - osx_image: xcode12.2
      env: DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=10.3.1'

    - osx_image: xcode12.2
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=14.2'
    - osx_image: xcode12.2
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=13.3'
    - osx_image: xcode12.2
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=12.4'
    - osx_image: xcode12.2
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=11.4'
    - osx_image: xcode12.2
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=10.2'
        
    - osx_image: xcode11.3
      env: DESTINATION='platform=OS X,arch=x86_64'
    - osx_image: xcode11.3
      env: DESTINATION='platform=OS X,arch=x86_64'
    - osx_image: xcode11.3
      env: DESTINATION='platform=OS X,arch=x86_64'

script:
  - swiftlint --strict
  - set -o pipefail && xcodebuild build -workspace $WORKSPACE -scheme $SCHEME -destination "${DESTINATION}" | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Logr'
