os: osx
osx_image: xcode11.5
language: swift

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

branches:
  only:
  - master
  - develop

before_install:
  - gem install xcpretty --no-document --quiet

jobs:
  include:
    - stage: Build
      script:
        - xcodebuild build -project Logr.xcodeproj -scheme Logr -destination 'platform=iOS Simulator,name=iPhone 5s,OS=10.3.1'
        - xcodebuild build -project Logr.xcodeproj -scheme Logr -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'

    - stage: Test
      script:
        - xcodebuild clean test -project Logr.xcodeproj -scheme Logr -destination 'platform=iOS Simulator,name=iPhone 5s,OS=10.3.1' | xcpretty -c && exit ${PIPESTATUS[0]}
        - xcodebuild clean test -project Logr.xcodeproj -scheme Logr -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest' | xcpretty -c && exit ${PIPESTATUS[0]}

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Logr'
